Bump the go version to 1.18
1.17 has runtime errors:

```
fatal error: checkptr: converted pointer straddles multiple allocations
```

GO11MODULE behavior changed in 1.17 so README.md is updated accordingly.